	.title	ENUBUG
	.enabl	LC

	.asect
	.=1000

Start:	mov	#PPUSta, R4			; run PPU code
	mov	#PPUEnd-PPUSta/2, R5
	call	PPRun

	tst	PpuKey
	beq	.-4

	call	PPRel
	emt	350

; //////////////////////////////////////////////////////////////////////////////
; // CPU -> PPU exchange	
; //////////////////////////////////////////////////////////////////////////////

; PPU message
;
PPComm:	.word	177777				; our custom command to PPU
PPmsg:	.word	PPArr				; address of beginning of array
        .word	177777				; end of transmission

; PPU data exchange array
;
PPArr:	.byte	0				; return value (0 - OK)
PPCmd:	.byte	0				; command
	.word	32				; device type (32 - PPU mem)
PPApp:	.word	0				; address for PPU
PPAcp:	.word	0				; address for CPU / length for allocate
PPLen:	.word	0				; length in words

; send command to PPU
PPSen:	mov	R0, -(SP)
	mov	R1, -(SP)
	mov	#PPMsg, R0			; array address
	mov	#5, R1				; bytes to send+1 (sending from @#PP_MSG)
	br	10$
20$:	movb	(R0)+, @#176676
10$:	tstb	@#176674			; test if we are ready to send
	bpl	10$				; cycle if >= 0 (not set last bit in byte)
	sob	R1, 20$
	mov	(SP)+, R1
	mov	(SP)+, R0
	return

; send and start PPU code
; R4 - start addr in CPU
; R5 - length / 2
PPRun:	mov	PC, PPComm			; set 'command' as not zero
	movb	#1, PPCmd			; 1 - allocate memory
	mov	R5, PPAcp
	call	PPSen				; (!) no checking for error
	movb	#20, PPCmd			; 20 - write to PPU mem
	mov 	R4, PPAcp
	mov	R5, PPLen
	call	PPSen
	movb	#30, PPCmd			; 30 - run
	call	PPSen
	tst	PPComm				; wait for PPU code up and running
	bne	.-4
	return

; release PPU memory
PPRel:	mov	#177777, PPComm			; ask PPU to exit 
	tst	PPComm				; wait for ackn
	bne	.-4
	movb	#2, PPCmd			; 2 - release memory
	br	PPSen


; //////////////////////////////////////////////////////////////////////////////	
; // PPU
; //////////////////////////////////////////////////////////////////////////////

; PPU starting addr
PPUSta:	mtps	#200
	clr	R0
	call	@7132(R0)			; stop FD motor

	mov	#177010, R4
	mov	#177014, R5

	; grab keyboard interrupt
	mov	@#300, -(SP)			; save old key int addr
	mov	PC, R0
	add	#PpuKeyInt-., R0
	mov	R0, @#300

; setup lines table
PpuSetVlines:
	mov	PC, R0
	add	#PpuLines+7-., R0
	bic	#7, R0				; R0 - line table start addr
	mov	R0, -(SP)			; save it
	bis	#6, (SP)			; +6 means first line descriptor have color
	mov	#^B1101110010011000, (R0)+	; YRGB YRGB YRGB YRGB for colors 1st part
	mov	#^B1111111010111010, (R0)+	; YRGB YRGB YRGB YRGB for colors 2nd part
	clr	(R0)+				; vaddr not used for first 18 lines
	mov	R0, (R0)
	add	#2, (R0)
	bis	#2, (R0)+			; +2 means next line is scale&cursor
	mov	#^B0000000000010000, (R0)+	; black colored graph cursor
	mov	#^B0000000000000111, (R0)+	; max luminance (xxxDDxBGR, DD: 00-640, 01-320, 10-160, 11-80)
	clr	(R0)+				; vaddr still not needed
	mov	R0, (R0)
	add	#2, (R0)+			; +0 means next line is 2-word descriptor
	; 16. not used lines
	mov	#16., R3
10$:	clr	(R0)+
	mov	R0, (R0)
	add	#2, (R0)+
	sob	R3, 10$
	; 288. main lines
	mov	#288., R3
	mov	#100000, R1
	mov	R0, -(SP)			; store top
20$:	mov	R1, (R0)+			; put vaddr
	mov	R0, (R0)			; put next element addr
	add	#2, (R0)+
	sub	#80., R1			; decrease vaddr
	sob	R3, 20$
	; cycle to top
	mov	(SP)+, -(R0)
	; set lines
	mov	@#272, R0
	mov	(SP)+, @#272
	mov	R0, -(SP)

	mov	#PPComm/2, (R4)
	clr	(R5)
	mtps	#0

PpuMai:	mov	#PPComm/2, (R4)
	tst	(R5)
	beq	PpuMai

	mov	(SP)+, @#272
	mov	(SP)+, @#300
	clr	(R5)
	return

; PPU keyboard interrupt (signal to CPU that we released anykey)
PpuKeyInt:
	mov	(R4), -(SP)
	mov	R0, -(SP)
	movb	@#177702, R0			; key press or release
	bpl	10$				; released
	mov	#PpuKey/2, (R4)
	movb	R0, (R5)
	movb	R0, PpuKey
10$:	mov	(SP)+, R0
	mov	(SP)+, (R4)
	rti

PpuKey:		.word	0
PpuLines:	.blkw	288.+16.*2+8.+4.

PPUEnd:

	.end	Start
